baseURL = 'https://finance-blog.mkarakiapps.com/'
languageCode = 'ja-jp'
defaultContentLanguage = 'ja'
title = 'Finance Blog'
theme = 'clarity'

hasCJKLanguage = true

timeZone = 'Asia/Tokyo'

[params]
    DateFormat = "2006/01/02"
    customCSS = [ "https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" ]